name: Release

on:
  pull_request: {}
  push:
    tags:
      - "release/*"

jobs:
  package:
    strategy:
      matrix:
        architecture: [amd64, arm64, arm]
        include:
          - architecture: amd64
            target: x86_64-unknown-linux-gnu
            strip: strip
          - architecture: arm64
            target: aarch64-unknown-linux-gnu
            strip: aarch64-linux-gnu-strip
          - architecture: arm
            target: armv7-unknown-linux-gnueabihf
            strip: arm-linux-gnueabihf-strip
    name: Package (${{ matrix.architecture }})
    runs-on: ubuntu-latest
    steps:
      - name: git co
        uses: actions/checkout@v1

      - name: meta
        id: release-tag-meta
        uses: ./.github/actions/release-tag-meta
        with:
          git-ref: ${{ github.ref }}
      #- run: echo "${{ toJSON(steps.release-tag-meta) }}"

      - name: package
        env:
          CARGO_RELEASE: "1"
          PACKAGE_VERSION: ${{ steps.release-tag-meta.outputs.name }}
          CARGO_TARGET: ${{ matrix.target }}
          STRIP: ${{ matrix.strip }}
        uses: ./.github/actions/package
        with:
          entrypoint: make
          args: package

      - name: checksec
        uses: ./.github/actions/package
        with:
          entrypoint: /linkerd/validate-checksec.sh
          args: /linkerd/expected-checksec.json "target/${{ matrix.target }}/release/package/linkerd2-proxy-${{ steps.release-tag-meta.outputs.name }}-checksec.json"
