name: release

on:
  push:
    tags:
      - "release/*"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: git co
        uses: actions/checkout@v1

      - name: meta
        id: release-tag-meta
        uses: ./.github/actions/release-tag-meta
        with:
          git-ref: ${{ github.ref }}

      - name: release
        uses: softprops/action-gh-release@b21b43d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.release-tag-meta.outputs.name }}
          files: target/x86_64-unknown-linux-gnu/release/package/*
